language: go

go:
  - "1.11.x"

env:
  - GO111MODULES=on GOLANGCI_LINT_VERSION=1.12.5

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v${GOLANGCI_LINT_VERSION}
  - GO111MODULE=on go mod vendor

script:
  - go test -race ./...
  - golangci-lint run .
